---
title: "UMAP for immune map - macrophage"
author: "Chen Zhan"
date: "2024-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries and data

```{r}
library(HDF5Array)
library(tidyverse)
library(SummarizedExperiment)
library(uwot)

hdf5 = loadHDF5SummarizedExperiment("pseudobulk_sample_cell_type/") 

metadata = hdf5 %>% colData()

macrophage_se <- hdf5[, hdf5$cell_type_consensus_harmonised == 'macrophage']

matrix_mac = macrophage_se %>% assay('counts_scaled') %>% as.matrix()

```

# Run Umap

```{r}
# Run UMAP on the converted matrix
umap_result <- umap(t(matrix_mac))  # Transpose if rows are genes and columns are cells

# Convert UMAP result to a data frame for plotting
umap_df <- as.data.frame(umap_result)
colnames(umap_df) <- c("UMAP1", "UMAP2")
```

# Merge metadata

```{r}

metadata = metadata %>% as.data.frame() %>% filter(cell_type_consensus_harmonised == 'macrophage')

metadata$Cell_ID <- row.names(metadata)  
umap_df$Cell_ID <- row.names(umap_df)

umap_df = merge(umap_df, metadata)
```

# Plot - dataset_id

```{r}
# Plot UMAP
library(ggplot2)
ggplot(umap_df, aes(x = UMAP1, y = UMAP2, color = dataset_id)) +
  geom_point(alpha = 0.7) +
  labs(title = "UMAP of Scaled Counts for Macrophages", x = "UMAP 1", y = "UMAP 2") +
  theme_minimal() +
  theme(legend.position = "none")  # Remove legend 
```

# Plot - assay_groups

```{r}
# Plot UMAP
library(ggplot2)
ggplot(umap_df, aes(x = UMAP1, y = UMAP2, color = assay_groups)) +
  geom_point(alpha = 0.7) +
  labs(title = "UMAP of Scaled Counts for Macrophages", x = "UMAP 1", y = "UMAP 2") +
  theme_minimal() 
```

# Plot - tissue_groups

```{r}
# Plot UMAP
library(ggplot2)
ggplot(umap_df, aes(x = UMAP1, y = UMAP2, color = tissue_groups)) +
  geom_point(alpha = 0.7) +
  labs(title = "UMAP of Scaled Counts for Macrophages", x = "UMAP 1", y = "UMAP 2") +
  theme_minimal() +
  theme(legend.position = "none")  # Remove legend 
```

# Plot - age_bin_sex_specific

```{r}
# Plot UMAP
library(ggplot2)
ggplot(umap_df, aes(x = UMAP1, y = UMAP2, color = age_bin_sex_specific)) +
  geom_point(alpha = 0.7) +
  labs(title = "UMAP of Scaled Counts for Macrophages", x = "UMAP 1", y = "UMAP 2") +
  theme_minimal() 
```

# Plot - sex

```{r}
# Plot UMAP
library(ggplot2)
ggplot(umap_df, aes(x = UMAP1, y = UMAP2, color = sex)) +
  geom_point(alpha = 0.7) +
  labs(title = "UMAP of Scaled Counts for Macrophages", x = "UMAP 1", y = "UMAP 2") +
  theme_minimal() 
```

# Plot - ethnicity_groups

```{r}
# Plot UMAP
library(ggplot2)
ggplot(umap_df, aes(x = UMAP1, y = UMAP2, color = ethnicity_groups)) +
  geom_point(alpha = 0.7) +
  labs(title = "UMAP of Scaled Counts for Macrophages", x = "UMAP 1", y = "UMAP 2") +
  theme_minimal() 
```
# Plot - collection_id

```{r}
# Plot UMAP
library(ggplot2)
ggplot(umap_df, aes(x = UMAP1, y = UMAP2, color = collection_id)) +
  geom_point(alpha = 0.7) +
  labs(title = "UMAP of Scaled Counts for Macrophages", x = "UMAP 1", y = "UMAP 2") +
  theme_minimal() +
  theme(legend.position = "none")  # Remove legend 
```
# Plot - disease_groups

```{r}
# Plot UMAP
library(ggplot2)
ggplot(umap_df, aes(x = UMAP1, y = UMAP2, color = disease_groups)) +
  geom_point(alpha = 0.7) +
  labs(title = "UMAP of Scaled Counts for Macrophages", x = "UMAP 1", y = "UMAP 2") +
  theme_minimal() +
  theme(legend.position = "none")  # Remove legend 
```